/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projetoindividual;

import java.util.Random;

/**
 *
 * @author Aluno
 */
public class ProjetoIndividual extends javax.swing.JFrame {

    Integer contador = 0;
   
    Integer maximoCpu = 0, minimoCpu = 100;
    Integer maximoDisco = 0, minimoDisco = 100;
    Integer maximoMemoria = 0, minimoMemoria = 100;

    Double mediaCpu = 0.0, mediaDisco = 0.0, mediaMemoria = 0.0;
    Double mediaFinalCpu, mediaFinalDisco,mediaFinalMemoria;

    /**
     * Creates new form ProjetoIndividual
     */
    public ProjetoIndividual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelCPU = new javax.swing.JLabel();
        LabelDisco = new javax.swing.JLabel();
        LabelMemoria = new javax.swing.JLabel();
        pbCpu = new javax.swing.JProgressBar();
        pbDisco = new javax.swing.JProgressBar();
        pbMemoria = new javax.swing.JProgressBar();
        ButtonLeitura = new javax.swing.JButton();
        TxtDisco = new javax.swing.JTextField();
        TxtCpu = new javax.swing.JTextField();
        TxtMemoria = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMaxCpu = new javax.swing.JTextField();
        txtMinCpu = new javax.swing.JTextField();
        txtMaxDisco = new javax.swing.JTextField();
        txtMedCpu = new javax.swing.JTextField();
        txtMedDisco = new javax.swing.JTextField();
        txtMinDisco = new javax.swing.JTextField();
        txtMinMemoria = new javax.swing.JTextField();
        txtMaxMemoria = new javax.swing.JTextField();
        txtMedMemoria = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(java.awt.Color.green);

        LabelCPU.setText("CPU:");

        LabelDisco.setText("Disco");

        LabelMemoria.setText("Memória");

        ButtonLeitura.setBackground(new java.awt.Color(0, 102, 0));
        ButtonLeitura.setText("Fazer leitura");
        ButtonLeitura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLeituraActionPerformed(evt);
            }
        });

        TxtDisco.setBackground(new java.awt.Color(255, 0, 0));
        TxtDisco.setForeground(new java.awt.Color(255, 255, 255));
        TxtDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDiscoActionPerformed(evt);
            }
        });

        TxtCpu.setBackground(new java.awt.Color(0, 0, 204));
        TxtCpu.setForeground(new java.awt.Color(255, 255, 255));
        TxtCpu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCpuActionPerformed(evt);
            }
        });

        TxtMemoria.setBackground(new java.awt.Color(51, 255, 51));
        TxtMemoria.setForeground(new java.awt.Color(255, 255, 255));
        TxtMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtMemoriaActionPerformed(evt);
            }
        });

        jLabel1.setText("Maximo");

        jLabel2.setText("Maximo");

        jLabel3.setText("Maximo");

        jLabel4.setText("Mínimo");

        jLabel5.setText("Mínimo");

        jLabel6.setText("Mínimo");

        jLabel7.setText("Média");

        jLabel8.setText("Média");

        jLabel9.setText("Média");

        txtMaxCpu.setBackground(new java.awt.Color(0, 0, 204));
        txtMaxCpu.setForeground(new java.awt.Color(255, 255, 255));
        txtMaxCpu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaxCpuActionPerformed(evt);
            }
        });

        txtMinCpu.setBackground(new java.awt.Color(0, 0, 204));
        txtMinCpu.setForeground(new java.awt.Color(255, 255, 255));
        txtMinCpu.setCaretColor(new java.awt.Color(0, 153, 51));
        txtMinCpu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinCpuActionPerformed(evt);
            }
        });

        txtMaxDisco.setBackground(new java.awt.Color(255, 0, 0));
        txtMaxDisco.setForeground(new java.awt.Color(255, 255, 255));
        txtMaxDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaxDiscoActionPerformed(evt);
            }
        });

        txtMedCpu.setBackground(new java.awt.Color(0, 0, 0));
        txtMedCpu.setForeground(new java.awt.Color(255, 255, 0));
        txtMedCpu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedCpuActionPerformed(evt);
            }
        });

        txtMedDisco.setBackground(new java.awt.Color(0, 0, 0));
        txtMedDisco.setForeground(new java.awt.Color(255, 255, 0));
        txtMedDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedDiscoActionPerformed(evt);
            }
        });

        txtMinDisco.setBackground(new java.awt.Color(255, 0, 0));
        txtMinDisco.setForeground(new java.awt.Color(255, 255, 255));
        txtMinDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinDiscoActionPerformed(evt);
            }
        });

        txtMinMemoria.setBackground(new java.awt.Color(0, 255, 0));
        txtMinMemoria.setForeground(new java.awt.Color(255, 255, 255));
        txtMinMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinMemoriaActionPerformed(evt);
            }
        });

        txtMaxMemoria.setBackground(new java.awt.Color(0, 255, 0));
        txtMaxMemoria.setForeground(new java.awt.Color(255, 255, 255));
        txtMaxMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaxMemoriaActionPerformed(evt);
            }
        });

        txtMedMemoria.setBackground(new java.awt.Color(0, 0, 0));
        txtMedMemoria.setForeground(new java.awt.Color(255, 255, 255));
        txtMedMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedMemoriaActionPerformed(evt);
            }
        });

        jLabel10.setToolTipText("");

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel11.setText("Desempenho");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel11)
                                .addGap(33, 33, 33)
                                .addComponent(ButtonLeitura))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(LabelDisco)
                                .addGap(18, 18, 18)
                                .addComponent(TxtDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addGap(35, 35, 35))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pbMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtMaxMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(LabelMemoria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LabelCPU)
                                        .addGap(18, 18, 18)
                                        .addComponent(TxtCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(68, 68, 68)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtMaxCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaxDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(43, 43, 43)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtMinDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtMinCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtMinMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtMedCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMedDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMedMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(37, 37, 37))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addGap(36, 36, 36)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pbCpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pbDisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonLeitura)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelCPU)
                        .addComponent(TxtCpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pbCpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMaxCpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMinCpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMedCpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDisco)
                    .addComponent(TxtDisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pbDisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMaxDisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMinDisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMedDisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelMemoria)
                    .addComponent(TxtMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMaxMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMinMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMedMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pbMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(150, 150, 150))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonLeituraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLeituraActionPerformed
        // Gera numeros aleatórios
        Random aleatorio = new Random();

        Integer valorCpu = aleatorio.nextInt(101);
        Integer valorDisco = aleatorio.nextInt(101);
        Integer valorMemoria = aleatorio.nextInt(101);

        //Os  numeros Maximo e Minimo da CPU
        if (valorCpu > maximoCpu) {
            maximoCpu = valorCpu;
        }
        if (valorCpu < minimoCpu) {
            minimoCpu = valorCpu;
        }
        //Os  numeros Maximo e Minimo do Disco
        if (valorDisco > maximoDisco) {
            maximoDisco = valorDisco;
        }
        if (valorDisco < minimoDisco) {
            minimoDisco = valorDisco;
        }
        //Os  numeros Maximo e Minimo da Memoria
        if (valorMemoria > maximoMemoria) {
            maximoMemoria = valorMemoria;
        }
        if (valorMemoria < minimoMemoria) {
            minimoMemoria = valorMemoria;
        }
        contador++;
        
        //Construção da média
        mediaCpu = (mediaCpu + valorCpu);
        mediaDisco = (mediaDisco + valorDisco);
        mediaMemoria = (mediaMemoria + valorMemoria);

        mediaFinalCpu = mediaCpu / contador;
        mediaFinalDisco = mediaDisco / contador;
        mediaFinalMemoria = mediaMemoria / contador;

     
        TxtCpu.setText(String.valueOf(valorCpu));
        txtMaxCpu.setText(String.valueOf(maximoCpu));
        txtMinCpu.setText(String.valueOf(minimoCpu));
        txtMedCpu.setText(String.valueOf(String.format("%.2f", (mediaFinalCpu))));

        TxtDisco.setText(String.valueOf(valorDisco));
        txtMaxDisco.setText(String.valueOf(maximoDisco));
        txtMinDisco.setText(String.valueOf(minimoDisco));
        txtMedDisco.setText(String.valueOf(String.format("%.2f", (mediaFinalDisco))));

        TxtMemoria.setText(String.valueOf(valorMemoria));
        txtMaxMemoria.setText(String.valueOf(maximoMemoria));
        txtMinMemoria.setText(String.valueOf(minimoMemoria));
        txtMedMemoria.setText(String.valueOf(String.format("%.2f", (mediaFinalMemoria))));

        pbCpu.setValue(valorCpu);
        pbDisco.setValue(valorDisco);
        pbMemoria.setValue(valorMemoria);

        
    }//GEN-LAST:event_ButtonLeituraActionPerformed

    private void TxtDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDiscoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDiscoActionPerformed

    private void TxtCpuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCpuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCpuActionPerformed

    private void TxtMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtMemoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtMemoriaActionPerformed

    private void txtMaxCpuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaxCpuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaxCpuActionPerformed

    private void txtMinCpuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinCpuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinCpuActionPerformed

    private void txtMaxDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaxDiscoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaxDiscoActionPerformed

    private void txtMedCpuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedCpuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedCpuActionPerformed

    private void txtMedDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedDiscoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedDiscoActionPerformed

    private void txtMinDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinDiscoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinDiscoActionPerformed

    private void txtMinMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinMemoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinMemoriaActionPerformed

    private void txtMaxMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaxMemoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaxMemoriaActionPerformed

    private void txtMedMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedMemoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedMemoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjetoIndividual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjetoIndividual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjetoIndividual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjetoIndividual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjetoIndividual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonLeitura;
    private javax.swing.JLabel LabelCPU;
    private javax.swing.JLabel LabelDisco;
    private javax.swing.JLabel LabelMemoria;
    private javax.swing.JTextField TxtCpu;
    private javax.swing.JTextField TxtDisco;
    private javax.swing.JTextField TxtMemoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar pbCpu;
    private javax.swing.JProgressBar pbDisco;
    private javax.swing.JProgressBar pbMemoria;
    private javax.swing.JTextField txtMaxCpu;
    private javax.swing.JTextField txtMaxDisco;
    private javax.swing.JTextField txtMaxMemoria;
    private javax.swing.JTextField txtMedCpu;
    private javax.swing.JTextField txtMedDisco;
    private javax.swing.JTextField txtMedMemoria;
    private javax.swing.JTextField txtMinCpu;
    private javax.swing.JTextField txtMinDisco;
    private javax.swing.JTextField txtMinMemoria;
    // End of variables declaration//GEN-END:variables
}
